version: '3'
services:
    mongodb:
        build:
            dockerfile: ./docker/mongodb.dockerfile
            context: .
        image: pontalti/mongodb
        container_name: mongo_db
        networks: 
            - production-network

    node1:
        build:
            dockerfile: ./docker/app.dockerfile
            context: .
        image: pontalti/employe
        container_name: employe
        ports:
          - "8080:8080"
          - "8000:8000"
        networks: 
            - production-network
        depends_on:
            - "mongodb"
networks: 
    production-network:
        driver: bridge